### ISSUE TITLE
mapbox upload with optional tileset

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-cli-py#103]
It would be nice if the `mapbox upload` command didn't require TILESET. If ommited it should extract the username from the token and construct a random string just like if you upload in Mapbox Studio.

**Comment by perrygeo** [comment]
@andrewharvey This would certainly be possible but not without breaking backwards compatibility. For instance, if I type

```
mapbox upload perrygeo.geojson
```

There is no way to tell if I intend to stream data from stdin to the `perrygeo.geojson` tileset or if I'm referring to a geojson file by that name and asking for a random tileset.

Disambiguating the usage here would be possible but would break many user's existing scripts. As a result, I'm inclined to say we should keep the current behavior. 

An alternative, if your application needs random tileset names, is to generate the tileset identifier explicitly in your script.
