### ISSUE TITLE
Staticmap: size limit vs tile stitching for high resolution maps

### ISSUE THREAD

**Issue by daniel-j-h** [mapbox/mapbox-cli-py#19]
There's an implicit 1280x1280 pixel limit on the size.

For example, creating wallpapers for my Thinkpad X1 Carbon fails with an API error:

    mapbox staticmap --zoom 12 --size 2560 1440 --lat 52.500385 --lon 13.419779 mapbox.emerald out.png

It would be great, to either document that limit and catch the error already at the argparser level or provide transparent stitching, like @zugaldia does in his [wallmapper](https://github.com/zugaldia/wallmapper) (this may be out of scope, though).

**Comment by perrygeo** [comment]
@daniel-j-h I think validating the input is the way to go. The overlays make stitching properly pretty difficult (tile edge effects, etc) and I think we can leave that to wallmapper.
