### ISSUE TITLE
Tests fail when MAPBOX_ACCESS_TOKEN is set

### ISSUE THREAD

**Issue by perrygeo** [mapbox/mapbox-cli-py#33]
```
        result = runner.invoke(
            main_group,
            ['geocoding', '--reverse'],
            input='{0},{1}'.format(lon, lat),
            env={'MapboxAccessToken': 'bogus'})
>       assert result.exit_code == 0
E       assert -1 == 0
E        +  where -1 = <Result ConnectionError(u'Connection refused: GET https://api.mapbox.com/geoco...123xyz',)>.exit_code

tests/test_geocoding.py:93: AssertionError
```
where `MAPBOX_ACCESS_TOKEN=123xyz` is set in my environment. If I `unset MAPBOX_ACCESS_TOKEN` it works. 

@sgillies is this just a matter of `MAPBOX_ACCESS_TOKEN` taking precedence over `MapboxAccessToken`?

**Comment by sgillies** [comment]
@perrygeo yes. I want our customers to use all caps envars (priniciple of least surprise). Internally, however, many of us have $MapboxAccessToken because of cloud formation. I'm going to push a commit that makes precedence more clear.

**Comment by perrygeo** [comment]
This issue still persists. The tests should pass even if a developer's `MAPBOX_ACCESS_TOKEN` is set. Sending a PR shortly.
