### ISSUE TITLE
Add mapbox-datasets-update-features with stdin or file input

### ISSUE THREAD

**Issue by sgillies** [mapbox/mapbox-cli-py#36]
I'd like to make this possible:

``` bash
$ mapbox datasets create
$ fio cat a.shp b.shp c.shp | mapbox datasets update-features $id
```

reading a GeoJSON feature sequence from stdin, or reading from a GeoJSON feature collection file.

``` bash
$ mapbox datasets create
$ fio cat a.shp b.shp c.shp | fio collect > lolwut.json
$ mapbox datasets update-features $id lolwut.json
```

**Comment by rclark** [comment]
I intend to implement these functions:

- mapbox datasets put-features: stream in geojson, inserts and updates
- mapbox datasets delete-features: stream in ids, remove features
- mapbox datasets put-dataset: create/replace an entire dataset with whatever you pipe on stdin

I already wrote these out in a non-chunked, not-really-streaming fashion, and I hope to take a stab at using cligj to help here this afternoon / weekend.

**Comment by sgillies** [comment]
Stale.
