### ISSUE TITLE
Implement an HTTP cache

### ISSUE THREAD

**Issue by sgillies** [mapbox/mapbox-cli-py#43]
In https://github.com/mapbox/mapbox-sdk-py/issues/100 I proposed that we leave caching up to users of the SDK.

A command (`mapbox cache`?) for inspecting and clearing the cache would round this out.

**Comment by perrygeo** [comment]
It feels like caching belongs at the client level. My only concern about implementing caching on top of the sdk client (rather than in the sdk itself) is that we're one-level removed from the http request so we can't use any of the existing request caching libraries - most likely having to re-implement parts of those libs including cache keys, headers, invalidation, storage, etc. How heavy of a lift is that likely to be?

**Comment by sgillies** [comment]
Okay, you're right. I'm going to look at making the cache configurable so that we can use the in-memory when we want and a disk cache for the CLI.

**Comment by perrygeo** [comment]
With https://github.com/mapbox/mapbox-sdk-py/pull/101 merged, isn't that just a matter of the CLI passing in a different cachecontrol.cache object?

**Comment by sbma44** [comment]
Is there any concern about this making debugging more difficult as we support users? I'm imagining someone who has their ratelimit adjusted upward and expects CLI behavior to respond accordingly. Making plugging in a cache easy sounds great, but I would never expect a command line tool like `curl` to do this by default.

**Comment by perrygeo** [comment]
@sbma44 I think the idea would be to respect the HTTP headers so we really wouldn't be caching any more aggressively than the API tells us to.

Still, it might make sense to make caching off by default. Turn it on via an optional `--cache` or config file? @sgillies what did you have in mind for the interface and configuration?

**Comment by sgillies** [comment]
@sbma44 aren't the cache control and etag headers we send with geocoding responses a signal to clients that they can benefit from caching? Or are those intended mainly for CloudFront?

How about this: no caching by default until we've got the implications of account upgrading figured out and largely solved?

**Comment by sbma44** [comment]
@sgillies to date I think those headers have been considered solely in the context of CloudFront. Certainly we've never tuned them to my knowledge.

I like your proposed solution/stopgap: make caching easy, but not enabled by default.

**Comment by sgillies** [comment]
I'm going to table this until the CacheControl bug I mentioned in https://github.com/mapbox/mapbox-sdk-py/issues/100 gets fixed.

**Comment by perrygeo** [comment]
closed in https://github.com/mapbox/mapbox-sdk-py/issues/100
