### ISSUE TITLE
world files for static maps api

### ISSUE THREAD

**Issue by perrygeo** [mapbox/mapbox-cli-py#46]
We should add a `--worldfile` option the staticmaps command which would write a GDAL-recognizable world file alongside the image. This would help users to quickly grab a portion of their tilesets and load them into a local GIS viewer to compare to local data.

We'd need to determine the worldfile extension based on requested image.

Because the exact extent would only be know if bounds were provided, we could make it invalid to specify `--worldfile` with `--auto`. Or is the `--auto` behavior defined well enough to predict it?

**Comment by perrygeo** [comment]
One challenge is that the bounds are not specified exactly, rather the user inputs `zoom` and center `lat` and `lon`. We'd need to write some logic to determine bounds (really just need the upper-left corner) based on the image size and z, lat/lon.

**Comment by perrygeo** [comment]
there's been little interest in this feature so 👋  bye bye

**Comment by flackdl** [comment]
Hi @perrygeo , I know this is quite an old discussion, but it's exactly what I'm interested so I thought I'd ask here.

I've been trying to figure out how to generate a world file from a [mapbox static image](https://docs.mapbox.com/api/maps/#static-images).

Do you know of a solution for this?

EDIT: I just stumbled upon https://github.com/mapbox/mercantile which looks like it may be exactly what I'm looking for.

**Comment by delebash** [comment]
I am also interested in something like this.  I need to be able to georefence an rgb png tile.
