### ISSUE TITLE
mapbox upload not accepting arguments

### ISSUE THREAD

**Issue by perrygeo** [mapbox/mapbox-cli-py#52]
@planemad reports

```
$ mapbox upload username.tileset output.geojson 
Usage: mapbox upload [OPTIONS]
Error: Got unexpected extra arguments (username.tileset output.geojson)
```

**Comment by perrygeo** [comment]
@planemad Can you run `mapbox upload --help` and let me know what you get? Also, what method did you use to install (`sudo pip install mapbox`?)

**Comment by planemad** [comment]
@perrygeo 

The instructions says `pip install mapboxcli` are they different?

Anyway just did a `sudo -H pip install mapbox --upgrade`

And it works now :+1: thanks.
