### ISSUE TITLE
MapboxAccessToken or MAPBOX_ACCESS_TOKEN?

### ISSUE THREAD

**Issue by planemad** [mapbox/mapbox-cli-py#53]
[-help says](https://github.com/mapbox/mapbox-cli-py/blob/master/mapboxcli/scripts/cli.py#L52) its `MAPBOX_ACCESS_TOKEN` but using this gave me the error
```
Before running this command you must set a Mapbox access token to an environment
variable named MapboxAccessToken. The access token must include the "uploads:write"
scope. Learn more about access tokens at https://www.mapbox.com/developers/api/#access-tokens.
```

So I tried `export MapboxAccessToken=` and this did the trick. I'm running `v0.2.0`.

cc @perrygeo

**Comment by perrygeo** [comment]
@planemad That looks like the [usage text for `mapbox-upload`](https://github.com/mapbox/mapbox-upload/blob/master/USAGE.txt#L7-L9) not `mapbox upload` :-)

For `mapbox upload`, everything should work by setting `MAPBOX_ACCESS_TOKEN`, `MapboxAccessToken`  or both. We use the CamelCase version as a fallback for backwards compatibility but the ALL_CAPS version takes precedence.

**Comment by planemad** [comment]
@perrygeo yikes, that was right.
