### ISSUE TITLE
Upload: add ability to set data/tileset privacy

### ISSUE THREAD

**Issue by marracci** [mapbox/mapbox-cli-py#64]
Currently, using upload still require user to manually go into Studio and set new tileset rights to public (default is private). Would be great to have a function added that sets privacy via CLI, especially in cases where upload replaces an existing tileset that is already exposed via styles.

maybe something like: `mapbox upload <TILESET> <INFILE>  (public,private)`

**Comment by perrygeo** [comment]
@marracci Thanks! 

Currently, the [uploads API](https://www.mapbox.com/developers/api/uploads/) itself doesn't support setting the permissions; everything is private by default as you said. If API-level support for setting permissions is released in a future version, we'll definitely include that here!

**Comment by sgillies** [comment]
Old issue. We'll revisit if possible.
