### ISSUE TITLE
No read method on valid file upload

### ISSUE THREAD

**Issue by wboykinm** [mapbox/mapbox-cli-py#67]
Just got this somewhat-cryptic message on trying to upload [this valid demo geojson file](https://gist.github.com/wboykinm/63bc9c44d6672a0aeda2)
```
| => mapbox upload --name landplanner.demopoints demo.geojson
Usage: mapbox upload [OPTIONS] TILESET [INFILE]

Error: Invalid value: Object `None` has no .read method, a file-like object is required
```

My key is properly configured (I gave it all 12 scopes just in case) and exported to `$MAPBOX_ACCESS_TOKEN`, and the file is valid, so I'm not sure what's going on here. Is my account missing some authorization globally?

**Comment by perrygeo** [comment]
@wboykinm I think it's just a mix up in the command line arguments. `demo.geojson` was interpreted as the `TILESET` arg leaving the `INFILE` argument blank.

This should work
```
$ mapbox upload --name "Demo Points Title" landplanner.demopoints demo.geojson

                |------------------------| |--------------------| |----------|
                     Title in Studio             Tileset ID        input data
```

To clarify
* `--name` is optional and defines the human-readable title you'll see in Studio
* `TILESET` is required and defines the tileset id (with the `<username>.<textid>` pattern)
* `INFILE` is the local data and *should be* required.

<hr>

The **cryptic error message** is definitely a problem. `INFILE` should probably be a required argument and give a useful error message
```
Error: Missing argument "INFILE".
```
It appears to be [explicitly not required](https://github.com/mapbox/mapbox-cli-py/blob/master/mapboxcli/scripts/uploads.py#L9) so I'll have to review why that's the case.

**Comment by perrygeo** [comment]
@wboykinm thanks for the report. The above PR should at least make the error messages clear in the next version.

**Comment by wboykinm** [comment]
Awesome; thanks!

**Comment by wboykinm** [comment]
Resolved on my end. Thanks again @perrygeo.
