### ISSUE TITLE
Trouble setting access token

### ISSUE THREAD

**Issue by andrewpatterson3001** [mapbox/mapbox-cli-py#69]
Hello,

I'm a junior developer and I'm playing around with the Mapbox CLI. I installed through Homebrew with no problems, but when I tried setting the token as per the instructions here on Github:

`$ mapbox --access-token tokenfromstudiohomepagegoeshere12323342423442`

I'm getting 

    Usage: mapbox [OPTIONS] COMMAND [ARGS]...
    Error: Missing command.

Is there something basic I'm missing here?

**Comment by perrygeo** [comment]
@andrewpatterson3001 The access token is likely fine, but you need to specify a command. If you type `mapbox --help` you'll see a list of available commands. To get the details of each command,  `mapbox COMMAND --help`

A quick way to test is to run the `geocoding` command, example:

    mapbox --access-token tokenfromstudio... geocoding "Washington DC"

Also, to avoid having to type the access token each time, I'd recommend setting your token as an environment variable 

```
export MAPBOX_ACCESS_TOKEN=tokenfromstudio...
mapbox geocoding "Washington DC"
```
Let me know if that works for you.

**Comment by andrewpatterson3001** [comment]
Yes, both ways work well. Thank you! I was mistaken in thinking that the original way I tried would set the environment variable and I wouldn't have to re-enter it.
