### ISSUE TITLE
mapbox returns driving instead of walking directions

### ISSUE THREAD

**Issue by JayBrown** [mapbox/mapbox-cli-py#71]
I'm currently testing mapbox results for walking directions from one location to a public transportation stop/station in the Berlin area (Germany). However, mapbox returns only driving directions. The question is, if I'm doing something wrong, or if mapbox is simply incapable of handling such a request.

These are the commands:
```
MB_DIRECTIONS=$(mapbox directions "[$CURRENT_LONG, $CURRENT_LAT]" "[$STATION_LONG, $STATION_LAT]" --profile mapbox.walking --alternatives)
MB_INSTRUCTIONS=$(echo "$MB_DIRECTIONS" | jq '.routes[0].steps[] .maneuver.instruction' -M -r)
MB_DISTANCES=$(echo "$MB_DIRECTIONS" | jq '.routes[0].steps[] .distance' -M -r)
```
Variables for current lat/long and station lat/long are defined earlier.

This is the mapbox result (note the difference between linear and "walking" distance):
```
From: Herbert-von-Karajan-Straße 1, Berlin, Berlin 10785, Germany [52.510032,13.369693]
To: Potsdamer Straße, Berlin, Berlin 10785, Germany [52.507568,13.369186]

109	 	Head right
40		Turn right onto Tiergartenstraße (L 1137) at the end of the road
216		Turn right onto Ben-Gurion-Straße
153		Turn right onto Potsdamer Straße (B 1)
21		Turn left onto Potsdamer Straße
115		Turn right onto Potsdamer Straße (B 1) at the end of the road
0		You have arrived at your destination, on the right

Linear Distance: 275.9384 Meters
Walking Distance: 654 Meters
Approximate Walking Time: 8 Minutes
```

This is the (accurate) result in Apple Maps:
http://i.imgur.com/zLhpMQI.png

So Mapbox sends me the completely wrong way, north first, then east, then south, then onto the actual destination street, but not without a u-turn later on. These are clearly driving directions, and not even those are the fastest ones possible.

What's wrong here?

**Comment by freenerd** [comment]
This is a data problem on OpenStreetMap. The pedestrian road that you are seeing on Apple maps is not currently represented in OpenStreetMap. Mapbox Directions is "snapping" to the nearest road, which for your coordinates is the road to the north.

You can actually fix this specific problem yourself by adding the roads in OpenStreetMap. Within the next 2 days the change should then be represented in Mapbox Directions.

Here is the current map:

<img width="789" alt="screen shot 2016-05-25 at 10 08 54" src="https://cloud.githubusercontent.com/assets/25713/15542991/0aa27d1a-2261-11e6-8fb2-145131ce47e2.png">

https://www.openstreetmap.org/#map=18/52.50935/13.37072

When you switch to edit mode you can see from the satellite image which road should be added:

<img width="1035" alt="screen shot 2016-05-25 at 10 11 48" src="https://cloud.githubusercontent.com/assets/25713/15543004/1b3b46ca-2261-11e6-8d4a-b43539db46e2.png">

https://www.openstreetmap.org/edit#map=18/52.50938/13.37024
