### ISSUE TITLE
0.4 release

### ISSUE THREAD

**Issue by perrygeo** [mapbox/mapbox-cli-py#74]
@sgillies let's coordinate on a new release, it's been a while and I want to make sure our release process is ironed out, esp. with homebrew builds.

I've started a 0.4 milestone with @mattficke's work on geocoding bbox support and my upload arg change PR.

https://github.com/mapbox/mapbox-cli-py/pulls?q=is%3Apr+is%3Aopen+milestone%3A0.4

Anything else we want to get it for 0.4?

**Comment by sgillies** [comment]
Target for release: Tuesday 6/14.
