### ISSUE TITLE
Access Token missing command

### ISSUE THREAD

**Issue by DenisCarriere** [mapbox/mapbox-cli-py#82]
Getting this error with the command line.

```bash
$ mapbox --access-token <ACCESS TOKEN>
Usage: mapbox [OPTIONS] COMMAND [ARGS]...

Error: Missing command.
```

**Comment by vincentsarago** [comment]
Hi @DenisCarriere, 

You have to pass one of those command:

```
config       Show all config settings.
datasets     Read and write Mapbox datasets (has subcommands)
directions   Routing between waypoints.
distance     Distance matrix of travel times between waypoints.
geocoding    Geocode an address or coordinates.
mapmatching  Snap GPS traces to OpenStreetMap
staticmap    Static map images.
surface      Surface profiles from vector tiles
upload       Upload datasets to Mapbox accounts
```

`--access-token` is not a command but an option if you don't want to use the env variable method `export MAPBOX_ACCESS_TOKEN=MY_TOKEN` 

so you have to do something like 
`mapbox datasets list --access-token {YOUR-TOKEN}`

**Comment by sgillies** [comment]
Thanks @vincentsarago!

**Comment by DenisCarriere** [comment]
@vincentsarago Thanks for the explanation! This makes sense now.

**Comment by lorenzori** [comment]
don't know if this has changed now, but if I run:
`mapbox datasets list --access-token <access_token>`

I get the error:
`Error: no such option: --access-token`

**Comment by vincentsarago** [comment]
👋 Hi @lorenzori 
This is my bad, you have to pass the `--access-token` before the subcommands like:

`mapbox  --access-token <access_token>  datasets list`

hope it helps!

**Comment by lorenzori** [comment]
ah thanks for the quick reply, works like charm!
