### ISSUE TITLE
deprecate mapbox-upload in favor of mapbox-cli-py?

### ISSUE THREAD

**Issue by mapsam** [mapbox/mapbox-cli-py#83]
It'd be good to deprecate one of our CLI upload tools, [mapbox-upload](https://github.com/mapbox/mapbox-upload), so we can focus development and fixes in a single repo. Mapbox-cli-py is our go-to CLI tool, and should be able to do all of the work mapbox-upload does.

On first glance, it doesn't do anything more than this CLI, so it shouldn't be a huge lift. I'll do more digging to make sure all features are carried over.

cc @rclark @willwhite @perrygeo @mattficke @sgillies

**Comment by willwhite** [comment]
Yes, sounds like a great idea to me. Thanks for taking this on.

**Comment by sgillies** [comment]
@mapsam shall we enumerate the features mapbox-cli-py upload lacks?

* upload from S3 as well as local file
* progress bar (possible with http://click.pocoo.org/5/utils/#showing-progress-bars)

**Comment by sgillies** [comment]
I've checked the usage of `mapbox-upload` around various projects and after we ship version 0.6 of mapbox-cli-py migration, migration of a bash script won't be much more than `s/mapbox-upload/mapbox upload/g`.
