### ISSUE TITLE
Add CLI for Analytics API

### ISSUE THREAD

**Issue by amishas157** [mapbox/mapbox-cli-py#93]
Based on [Analytics SDK](https://github.com/mapbox/mapbox-sdk-py/issues/153), add support for Analytics API

`mapbox analytics [args]`

-- resource_type
-- username
-- id 
-- start
-- end
-- MAPBOX_ACCESS_TOKEN

cc @sgillies @perrygeo @batpad

**Comment by sgillies** [comment]
@amishas157 

In general, let's try to be compatible with the GNU standards for command line options here: https://www.gnu.org/prep/standards/html_node/Option-Table.html#Option-Table. What you've sketched will be fine with one change: `--resource-type` for `--resource_type`. We've got precedent in `mapbox geocode` for `-t` as a short name for `--place-type` and so we can use `-t` here as a shortcut for `--resource-type`.

Commands get their access token from their "context" like this: https://github.com/mapbox/mapbox-cli-py/blob/master/mapboxcli/scripts/geocoding.py#L97. You won't have to write any other code to get it from the command line.

**Comment by andrewharvey** [comment]
Looks like the Analytics API was deprecated

**Comment by jqtrde** [comment]
Yes, thanks @andrewharvey :+1:
