### ISSUE TITLE
upload fails due to unicode encode error

### ISSUE THREAD

**Issue by jliebrand** [mapbox/mapbox-cli-py#97]
To reproduce, grab the docker image "savvynavvy/buildpack" and then try to use the mapbox cli to upload a tileset.

Error:

```
 File "/usr/local/lib/python2.7/dist-packages/mapboxcli/scripts/uploads.py", line 71, in upload
    callback=callback)
  File "/usr/local/lib/python2.7/dist-packages/mapbox/services/uploads.py", line 157, in upload
    url = self.stage(fileobj, callback=callback)
  File "/usr/local/lib/python2.7/dist-packages/mapbox/services/uploads.py", line 70, in stage
    bucket.upload_fileobj(fileobj, creds['key'], Callback=callback)
  File "/usr/local/lib/python2.7/dist-packages/boto3/s3/inject.py", line 469, in bucket_upload_fileobj
    Callback=Callback, Config=Config)
  File "/usr/local/lib/python2.7/dist-packages/boto3/s3/inject.py", line 427, in upload_fileobj
    return future.result()
  File "/usr/local/lib/python2.7/dist-packages/s3transfer/futures.py", line 73, in result
    return self._coordinator.result()
  File "/usr/local/lib/python2.7/dist-packages/s3transfer/futures.py", line 233, inresult
    raise self._exception
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2588' in position 31: ordinal not in range(128)

```

**Comment by perrygeo** [comment]
I'm a bit confused by the docker bit, are you saying the error only occurs inside of that container?

Preferably we could isolate the error without adding docker to the mix: a dataset and a command should be all we need to reproduce it.

**Comment by jliebrand** [comment]
Sorry, yes you should be able to repro it without the docker part; that was just an easy way for you to see the various versions of boto3/python/mapboxcli etc that we have (in case it was due to some mismatch there)

**Comment by perrygeo** [comment]
And how might one reproduce this error? It would be helpful if you could provide any details: the dataset, the command that failed, the version numbers of the packages.

**Comment by jliebrand** [comment]
Let me see if I can be somewhat clearer.

Here are the three relevant python modules I use and their versions for reference:
+ pip show boto3
Name: boto3
Version: 1.4.4
Summary: The AWS SDK for Python
Home-page: https://github.com/boto/boto3
Author: Amazon Web Services
Author-email: UNKNOWN
License: Apache License 2.0
Location: /usr/local/lib/python2.7/dist-packages
Requires: jmespath, s3transfer, botocore
+ pip show mapboxcli
Name: mapboxcli
Version: 0.6.0
Summary: Command line interface to Mapbox Web Services
Home-page: https://github.com/mapbox/mapbox-cli-py
Author: Sean Gillies
Author-email: sean@mapbox.com
License: MIT
Location: /usr/local/lib/python2.7/dist-packages
Requires: six, click-plugins, mapbox, cligj, click
+ pip show s3transfer
Name: s3transfer
Version: 0.1.10
Summary: An Amazon S3 Transfer Manager
Home-page: https://github.com/boto/s3transfer
Author: Amazon Web Services
Author-email: kyknapp1@gmail.com
License: Apache License 2.0
Location: /usr/local/lib/python2.7/dist-packages
Requires: futures, botocore

Using those, just run:
```
mapbox upload --name foo-staging username.foo-staging foo.mbtiles
```

I tried adding the tileset I was using, but it's larger than what is allowed on github issues; lemme see if I can upload it elsewhere

**Comment by jliebrand** [comment]
see if this works:
https://wetransfer.com/downloads/b7a1a32c3b3c5a9fad9a8046d4a6a20c20170410171936/b90f39780f0c85bf10c3d1b9b1a7875e20170410171936/5300c7

**Comment by jliebrand** [comment]
The upload starts, gets to about 2% and then throws the error I pasted in the original report

**Comment by jliebrand** [comment]
(alternatively, to reproduce, run the mapbox upload command inside the docker image)

**Comment by jliebrand** [comment]
oh and this is running on Python 2.7.9

**Comment by perrygeo** [comment]
Thanks @jliebrand! I tried that command with the same version and was able to upload the mbtiles successfully.

```
$ mapbox --version
0.6.0

$ mapbox upload --name foo-staging perrygeo.foo-staging ~/Downloads/foo.mbtiles
Uploading data source  [████████████████████████████████████]  100%
```

Another follow up question: what version of `mapbox-sdk-py` do you have? My test environment is using

```
$ python -c "import mapbox; print(mapbox.__version__)"
0.12
```

**Comment by perrygeo** [comment]
I'm able to reproduce this but only from your Docker container. The same versions installed locally on mac and linux both work. 😕  Need to investigate a bit more...

**Comment by jliebrand** [comment]
Ah, great you are able to reproduce; yeah I suspect it's some odd combination of dependencies, but if it helps, the docker image is based on buildpack-deps:jessie-scm with pip installed via easy_install and mapboxcli installed via pip... (also tried installing python-pip via apt-get, same results)... Let me know if you need the Dockerfile

**Comment by perrygeo** [comment]
I was able to reproduce this on Ubuntu 16.04 using python 2.7.12. It happens regardless of the input file and only on Linux, cannot reproduce on OSX. 

I traced the error down to a very strange interaction between `boto3` and the `click` progressbar. We can remove mapboxcli from the equation for the sake of the most direct demonstration:

If I set up a boto3 session

```python
from boto3.session import Session as boto3_session
import click
import os
import sys

session = boto3_session()
s3 = session.resource('s3')
bucket = s3.Bucket('perrygeo-test')
```

Then upload using a click progressbar with an ascii character  (`fill_char="#"`), it works
```python
In [2]: with open('test.tif', 'rb') as fileobj:
   ...:     filelen = os.stat(fileobj.name).st_size
   ...:     with click.progressbar(length=filelen, fill_char="#", file=sys.stderr) as bar:
   ...:
   ...:         def callback(num_bytes):
   ...:             bar.update(num_bytes)
   ...:
   ...:         bucket.upload_fileobj(fileobj, 'test.tif', Callback=callback)
   ...:
  [####################################]  100%
```

But if use a unicode character (as mapbox cli does [here](https://github.com/mapbox/mapbox-cli-py/blob/7b159cf05b0e8da5124441141625462fcbdc000d/mapboxcli/scripts/uploads.py#L63)) for `fill_char`, the error occurs

```python
In [9]: with open('test.tif', 'rb') as fileobj:
   ...:     filelen = os.stat(fileobj.name).st_size
   ...:     with click.progressbar(length=filelen, fill_char=u"\u2588", file=sys.stderr) as bar:
   ...:
   ...:         def callback(num_bytes):
   ...:             bar.update(num_bytes)
   ...:
   ...:         bucket.upload_fileobj(fileobj, 'test.tif', Callback=callback)
   ...:
  [------------------------------------]    0%

UnicodeEncodeError                        Traceback (most recent call last)
...
UnicodeEncodeError: 'ascii' codec can't encode characters in position 10-19: ordinal not in range(128)
```


The callback never returns a value so it is perplexing how the boto3 code which calls it can fail when its merely manipulating the state of the progress bar. There is some wierd interaction here which I don't yet understand.

Regardless of the underlying cause, the fix is simple from the perspective of mapbox-cli: **just use an ascii fill character.**

@jliebrand I'll work up a pull request shortly. If you're able to modify your `mapboxcli/scripts/uploads.py`, you can patch the change into your application if you need it immediately.

**Comment by perrygeo** [comment]
@jliebrand New version is on pypi: https://pypi.python.org/pypi/mapboxcli/0.6.1

Let me know if this does the trick.

**Comment by jliebrand** [comment]
Ha! Who would have thought that an error about unicode encoding during upload_fileobj was actually completely unrelated to the data in the file!! :-)

Thanks for the amazingly quick turn around on this guys! 0.6.1 works like a charm on my side!
